### ISSUE TITLE
Unable to generate data

### ISSUE THREAD

**Issue by JohannesTK** [MostafaDehghani/bAbI-T2T#1]
Using command:

`t2t-datagen --problem=babi_qa_sentence_task15_10k --t2t_usr_dir=t2t_usr_dir --data_dir=t2t_data --tmp_dir=t2t_data/tmp`

Ends up with:

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/t2t-datagen", line 27, in <module>
    tf.app.run()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/ubuntu/.local/bin/t2t-datagen", line 23, in main
    t2t_datagen.main(argv)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensor2tensor/bin/t2t_datagen.py", line 182, in main
    generate_data_for_registered_problem(problem)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensor2tensor/bin/t2t_datagen.py", line 232, in generate_data_for_registered_problem
    problem.generate_data(data_dir, tmp_dir, task_id)
  File "/home/ubuntu/bAbI-T2T/t2t_usr_dir/babi_qa.py", line 202, in generate_data
    encoder = self.get_or_create_vocab(data_dir, tmp_dir)
AttributeError: 'BabiQaSentenceTask15_10k' object has no attribute 'get_or_create_vocab'
```

**Comment by MostafaDehghani** [comment]
Oh.. yes! Just fixed this in dcf8144. Thanks :)
